### ISSUE TITLE
Implementing exceptions to be thrown by implementations

### ISSUE THREAD

**Issue by Lctrs** [php-xapi/serializer#29]
Here is my proposal for this : 

1. Introduce a `ExceptionInterface`, an empty Interface that must be implemented by all Exceptions of this package.
2. Introduce 2 abstracts classes `SerializationException` and `DeserializationException` that will extend `\RuntimeException` and implement `ExceptionInterface`.
3. Introduce `StatementSerializationException`, `StatementDeserializationException`, etc. classes that extends either `SerializationException` or `DeserializationException`. I think you understand where they should be thrown.

WDYT ?

**Comment by xabbuh** [comment]
Sounds good as a base implementation to me. Could discuss if `RuntimeException` is the best its for the base class and if shouldn't use, for example, `DomainException` instead. I would also go one step further and introduce specialised exceptions for cases where mandatory data is missing or where additional data is present that couldn't be interpreted.

**Comment by xabbuh** [comment]
#30 is merged, but I would like to keep this issue open as a reminder that I want to expand the tests before the 3.0 release.
