### ISSUE TITLE
Compatibility with PHPUnit 6

### ISSUE THREAD

**Issue by Lctrs** [php-xapi/serializer#35]
Currently, builds in [php-xapi/symfony-serializer](https://github.com/php-xapi/symfony-serializer) on PHP 7 because Travis ships now with global PHPUnit 6, which is namespaced (See php-xapi/symfony-serializer#4).

To fix this, we can either :

- Upgrade our PHPUnit tests to support namespaces
- Or add our targeted PHPUnit version as a dev dependency in `composer.json` (like this : `phpunit/phpunit: ^5.0`) and make the Symfony Serializer tests run against it.

WDYT @xabbuh ?

**Comment by xabbuh** [comment]
I think we need a mix of both like what I did in php-xapi/client#24 (changing only the base test classes makes tests on older PHP versions fail as Travis uses totally outdated PHPUnit versions there).
